name: Build custom php unit docker image
on:
  push:
    branches:
      - wordpress_base
jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create image
        run: cd pkg/docker/ && make build-php7.4 VERSION_php=7.4
      - name: End Result
        run: echo "Hello World!"
