name: Build custom php unit docker image
on:
  push:
    branches:
      - wordpress_base
jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        id: github_container_registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create image
        run: cd pkg/docker/ && make build-php7.4 VERSION_php=7.4
      - name: Push Container Image
        run: |
          docker tag unit:1.26.1-php7.4 ghcr.io/nziswano/unit:1.26.1-php7.4
          docker push ghcr.io/nziswano/unit:1.26.1-php7.4
          echo "All done!"
